### PR TITLE
template refactoring

### PR DESCRIPTION
**Pull request by Mic92**

### CODE REVIEW

**Comment by hahuang65** [comment]
Wondering if this is on the roadmap, really hoping to use this in `home-manager`.

**Comment by Mic92** [comment]
Yes. It's still planned.

**Comment by jfly** [comment]
@Mic92, I've rebased the changes in this PR and completed the implementation in my fork: https://github.com/Mic92/sops-nix/compare/master...jfly:sops-nix:templates-refactoring.

**Comment by Mic92** [comment]
Will be continued in https://github.com/Mic92/sops-nix/pull/649

**Pull request closed without merging**
