### PR TITLE
home manager + nix darwin

### PR DESCRIPTION
**Pull request by pogobanane**
add darwin support to #168

### CODE REVIEW

**Comment by Mic92** [comment]
I will merge this when you can confirm that both home-manager and darwin works and have example configurations in the README.

**Comment by pogobanane** [comment]
successfully tested on
- with home-manager on darwin
- with home-manager on nixos
- globally on nixos

example configuration/documentation already converged in #168: https://github.com/pogobanane/sops-nix/tree/feat/home-manager-darwin#use-with-home-manager

Merging this PR will open a follow-up PR to rebase and merge into master.

**Comment by Mic92** [comment]
bors merge

**Comment by Mic92** [comment]
bors merge

**Pull request merged**
