### PR TITLE
Change sops decrypt url and update .gitignore

### PR DESCRIPTION
**Pull request by Janik-Haag**
Upstream changed their module url so I guess it's a good idea to updated it here.

### CODE REVIEW

**Comment by Janik-Haag** [comment]
Forgot to change the hash, should be fixed now.

**Comment by dasJ** [comment]
Sorry for the long holdup :/ Can you rebase again so we can get this in?

**Comment by Janik-Haag** [comment]
> Sorry for the long holdup :/ 

no worries

> Can you rebase again so we can get this in?

done 

I think the code has some regressions? There were some test failures after the update, and i think there are more now after doing the rebase, but I don't really have the time/energy to look into it currently. Feel free to force push to here.

**Comment by Mic92** [comment]
Thanks. Merged in https://github.com/Mic92/sops-nix/pull/512

**Pull request closed without merging**
